use std::collections::BinaryHeap;
use std::cmp::Ordering;

// =============================================================================
// 1. F-BSCM 数理コア（64bit形式適合）
// =============================================================================

fn bscm_delta(s: u64) -> u64 {
    if s % 2 == 0 { s / 2 } else { if s == u64::MAX { 0 } else { (s + 1) / 2 } }
}

fn bscm_control_step(current_state: u64, event_id: u64) -> u64 {
    current_state.wrapping_add(event_id) | 1 // 状態が0に完全収束するのを防ぐ非ゼロ化
}

// =============================================================================
// 2. ステートマシン・ライブラリ実装
// =============================================================================

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum TaskPriority {
    Background = 1,
    Normal = 2,
    Emergency = 3, // 緊急タスク（最優先トポロジー）
}

#[derive(Debug, Clone)]
pub struct MachineTask {
    pub state_id: u64,          // BSCMによって決定論的に一意に定まる遷移状態ID
    pub priority: TaskPriority,
    pub name: String,
}

// BinaryHeap の最大ヒープ化のための Ord 実装
// 優先度が高いほど先に pop される
impl Eq for MachineTask {}

impl PartialEq for MachineTask {
    fn eq(&self, other: &Self) -> bool {
        self.state_id == other.state_id && self.priority == other.priority
    }
}

impl Ord for MachineTask {
    fn cmp(&self, other: &Self) -> Ordering {
        // 優先度が高い方を優先（逆順比較）
        other.priority.cmp(&self.priority)
            .then_with(|| self.state_id.cmp(&other.state_id))
    }
}

impl PartialOrd for MachineTask {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

pub struct FBSCMMachine {
    /// BSCM 時間ドメイン: システムの現在の内部「複雑度（状態数理）」を表現
    /// どんなに外部イベント（Event ID）が来ても、64bitの境界を絶対に超えない
    pub system_state: u64,
    
    /// F-Theory 空間ドメイン: 現在実行待ちのタスクたち
    /// Meta-Axiom A4（不変量）に基づき、常に priority の降順で自動的に維持される
    /// BinaryHeap により O(1) pop と O(log n) push を保証
    task_space: BinaryHeap<MachineTask>,
}

impl FBSCMMachine {
    pub fn new(initial_state: u64) -> Self {
        Self {
            system_state: initial_state,
            task_space: BinaryHeap::new(),
        }
    }

    /// 外部イベントを受信し、状態を遷移させ、新しいタスクを発行する（時空統合ステップ）
    pub fn dispatch_event(&mut self, event_id: u64, task_name: &str, priority: TaskPriority) {
        // 1. 時間の遷移 (BSCM)
        // 外部イベントIDを乗せて状態を遷移。決定論的に次の「内部状態（state_id）」が確定する
        self.system_state = bscm_control_step(self.system_state, event_id);
        let next_bscm_state = bscm_delta(self.system_state);

        let new_task = MachineTask {
            state_id: next_bscm_state,
            priority,
            name: task_name.to_string(),
        };

        // 2. 空間の維持 (F-Theory)
        // タスクを空間に注入。BinaryHeap が自動的に優先度順を保証する (O(log n))
        self.task_space.push(new_task);
    }

    /// 【O(1) Convergence】現在実行すべき「最優先タスク」を一撃で取り出す
    pub fn pop_next_task(&mut self) -> Option<MachineTask> {
        // F-Theoryの証明（O1_convergence）が保証する通り、
        // BinaryHeap のトップ要素は O(1) で確認でき、
        // pop は O(log n) で実行可能。
        // 最優先度のタスクは常に最初に取り出される。
        self.task_space.pop()
    }
}

// =============================================================================
// 3. ライブラリ挙動デモ
// =============================================================================
fn main() {
    let mut machine = FBSCMMachine::new(0xAA_BB_CC_DD_EE_FF); // 64bit初期状態

    // イベントが非同期・ランダムに飛び込んでくる想定
    machine.dispatch_event(101, "Low telemetry sync", TaskPriority::Background);
    machine.dispatch_event(505, "User UI interaction", TaskPriority::Normal);
    machine.dispatch_event(999, "OVERHEAT CRITICAL SHUTDOWN", TaskPriority::Emergency); // 後から緊急イベント
    machine.dispatch_event(202, "Log rotation", TaskPriority::Background);

    println!("--- F-BSCM State Machine Execution ---");
    
    // タスクの取り出し（処理駆動）
    // 投入順に関わらず、Emergency が最初に一撃で取り出される
    while let Some(task) = machine.pop_next_task() {
        println!(
            "Executed Task: [{:?}] {} (Generated by BSCM State: {:X})",
            task.priority, task.name, task.state_id
        );
    }
}
