/-!
  ================================================================
  UHA-APEX-UNIFIED-PHYSICS-CORE  (revised)
  ================================================================

  Author : Takeo Yamamoto
  License: Apache-2.0

  Unified Formal Architecture:
    1. Dimension-Typed Syntax (Physical Dimension Safety)
    2. Gaussian Rational Complex Phase Space (q + i*p)
    3. Falsification, Momentum Consistency, optional Symmetry Filter
    4. Exact Rational Finite Difference & Certified Discovery

  Revision notes:
    * velocity is now the CENTERED difference (c.q - a.q) / (2 dt),
      consistent with the centered second difference used for acceleration.
    * isExact is proved equivalent to exactLaw (isExact_iff); the pipeline
      returns CertifiedLaw values, so every selected law carries its proof.
    * The translation test is an OPTIONAL sample-based filter, not Noether's
      theorem; it is no longer implied to be part of the core guarantee.
    * The momentum p of the phase point is used: p = m * v is checked.
    * Exact fits are only expected on data generated by the same discrete
      scheme (see `verlet`); real measurements need tolerance-based fitting.
-/

import Mathlib

open BigOperators

namespace UHA
namespace Unified

abbrev Scalar := ℚ

/-! ============================================================
    1. PHYSICAL DIMENSIONS
    ============================================================ -/

/-- [M] Mass, [L] Length, [T] Time exponents. -/
structure Dim where
  m : ℤ
  l : ℤ
  t : ℤ
deriving DecidableEq, Repr

namespace Dim

def dimensionless : Dim := ⟨0, 0, 0⟩
def length        : Dim := ⟨0, 1, 0⟩
def mass          : Dim := ⟨1, 0, 0⟩
def time          : Dim := ⟨0, 0, 1⟩
def velocity      : Dim := ⟨0, 1, -1⟩
def acceleration  : Dim := ⟨0, 1, -2⟩
def force         : Dim := ⟨1, 1, -2⟩

def mul (a b : Dim) : Dim := ⟨a.m + b.m, a.l + b.l, a.t + b.t⟩
def div (a b : Dim) : Dim := ⟨a.m - b.m, a.l - b.l, a.t - b.t⟩

end Dim

/-! ============================================================
    2. GAUSSIAN COMPLEX PHASE SPACE  z = q + i p
    ============================================================ -/

structure PhasePoint where
  re : Scalar -- q (position)
  im : Scalar -- p (momentum)
deriving DecidableEq, Repr

namespace PhasePoint

def q (z : PhasePoint) : Scalar := z.re
def p (z : PhasePoint) : Scalar := z.im

def add (a b : PhasePoint) : PhasePoint := ⟨a.re + b.re, a.im + b.im⟩
def sub (a b : PhasePoint) : PhasePoint := ⟨a.re - b.re, a.im - b.im⟩
def mul (a b : PhasePoint) : PhasePoint :=
  ⟨a.re * b.re - a.im * b.im, a.re * b.im + a.im * b.re⟩

end PhasePoint

structure Sample where
  t : Nat
  state : PhasePoint
deriving DecidableEq, Repr

abbrev Trajectory := List Sample

/-! ============================================================
    3. DIMENSION-TYPED PHYSICAL LAW AST
    ============================================================ -/

inductive TypedExpr : Dim → Type where
  | const (d : Dim) (c : Scalar) : TypedExpr d
  | q                            : TypedExpr Dim.length
  | p                            : TypedExpr (Dim.mul Dim.mass Dim.velocity)
  | v                            : TypedExpr Dim.velocity
  | add {d : Dim}                : TypedExpr d → TypedExpr d → TypedExpr d
  | sub {d : Dim}                : TypedExpr d → TypedExpr d → TypedExpr d
  | mul {d1 d2 : Dim}            : TypedExpr d1 → TypedExpr d2 → TypedExpr (Dim.mul d1 d2)
  | neg {d : Dim}                : TypedExpr d → TypedExpr d
  /-- Re-index by a proof that two dimensions are equal (e.g. [M L⁻²]·[L] = force). -/
  | cast {d d' : Dim} (h : d = d') : TypedExpr d → TypedExpr d'

namespace TypedExpr

def eval {d : Dim} (q p v : Scalar) : TypedExpr d → Scalar
  | .const _ c => c
  | .q         => q
  | .p         => p
  | .v         => v
  | .add a b   => eval q p v a + eval q p v b
  | .sub a b   => eval q p v a - eval q p v b
  | .mul a b   => eval q p v a * eval q p v b
  | .neg a     => -eval q p v a
  | .cast _ a  => eval q p v a

def size {d : Dim} : TypedExpr d → Nat
  | .const _ _ => 1
  | .q         => 1
  | .p         => 1
  | .v         => 1
  | .add a b   => 1 + size a + size b
  | .sub a b   => 1 + size a + size b
  | .mul a b   => 1 + size a + size b
  | .neg a     => 1 + size a
  | .cast _ a  => 1 + size a

end TypedExpr

/-- Only expressions of force dimension [M][L][T]⁻² are candidate laws. -/
abbrev ForceExpr := TypedExpr Dim.force

/-! ============================================================
    4. FINITE DIFFERENCE & REGRESSION (centered, consistent)
    ============================================================ -/

structure RegressionPoint where
  q : Scalar
  p : Scalar
  v : Scalar
  acceleration : Scalar
deriving DecidableEq, Repr

abbrev RegressionData := List RegressionPoint

/-- Centered velocity at the middle sample b: (c.q - a.q) / (2 dt). -/
def velocity (dt : Scalar) (a c : PhasePoint) : Scalar :=
  (c.q - a.q) / (2 * dt)

/-- Centered second difference at the middle sample b. -/
def acceleration (dt : Scalar) (a b c : PhasePoint) : Scalar :=
  (c.q - 2 * b.q + a.q) / (dt * dt)

def makeRegressionData (dt : Scalar) : Trajectory → RegressionData
  | a :: b :: c :: rest =>
      { q := b.state.q,
        p := b.state.p,
        v := velocity dt a.state c.state,
        acceleration := acceleration dt a.state b.state c.state } ::
      makeRegressionData dt (b :: c :: rest)
  | _ => []

/-! ============================================================
    5. FALSIFICATION, MOMENTUM CONSISTENCY, OPTIONAL SYMMETRY FILTER
    ============================================================ -/

def forceResidual (law : ForceExpr) (point : RegressionPoint) (mass : Scalar) : Scalar :=
  mass * point.acceleration - law.eval point.q point.p point.v

def isExact (law : ForceExpr) (data : RegressionData) (mass : Scalar) : Bool :=
  data.all (fun pt => decide (forceResidual law pt mass = 0))

def exactLaw (law : ForceExpr) (data : RegressionData) (mass : Scalar) : Prop :=
  ∀ pt ∈ data, forceResidual law pt mass = 0

def falsified (law : ForceExpr) (data : RegressionData) (mass : Scalar) : Prop :=
  ∃ pt ∈ data, forceResidual law pt mass ≠ 0

/-- The Boolean test and the logical statement agree. -/
theorem isExact_iff (law : ForceExpr) (data : RegressionData) (mass : Scalar) :
    isExact law data mass = true ↔ exactLaw law data mass := by
  unfold isExact exactLaw
  simp [List.all_eq_true]

theorem not_falsified_iff (law : ForceExpr) (data : RegressionData) (mass : Scalar) :
    ¬ falsified law data mass ↔ exactLaw law data mass := by
  simp [falsified, exactLaw]

theorem exactLaw_not_falsified (law : ForceExpr) (data : RegressionData) (mass : Scalar)
    (h : exactLaw law data mass) : ¬ falsified law data mass :=
  (not_falsified_iff law data mass).mpr h

/-- Uses the momentum component of the phase point: p = m * v at every sample. -/
def isMomentumConsistent (mass : Scalar) (data : RegressionData) : Bool :=
  data.all (fun pt => decide (pt.p = mass * pt.v))

/-- Sample-based translation test (NOT Noether's theorem): the law value is unchanged
    when q is shifted by c. Useful as an optional filter for free-particle-like laws;
    it must NOT be applied to laws such as a spring force. -/
def isTranslationInvariant (law : ForceExpr) (q p v c : Scalar) : Bool :=
  decide (law.eval (q + c) p v = law.eval q p v)

def translationFilter (data : RegressionData) (c : Scalar) : ForceExpr → Bool :=
  fun law => data.all (fun pt => isTranslationInvariant law pt.q pt.p pt.v c)

/-! ============================================================
    6. CERTIFIED DISCOVERY PIPELINE
    ============================================================ -/

structure CertifiedLaw where
  law : ForceExpr
  mass : Scalar
  data : RegressionData
  exactFit : exactLaw law data mass
  antiFalsification : ¬ falsified law data mass

def certify (law : ForceExpr) (mass : Scalar) (data : RegressionData)
    (h : exactLaw law data mass) : CertifiedLaw :=
  { law := law,
    mass := mass,
    data := data,
    exactFit := h,
    antiFalsification := exactLaw_not_falsified law data mass h }

/-- Boolean test succeeds → a proof-carrying certificate; otherwise none. -/
def tryCertify (law : ForceExpr) (mass : Scalar) (data : RegressionData) :
    Option CertifiedLaw :=
  if h : isExact law data mass = true then
    some (certify law mass data ((isExact_iff law data mass).mp h))
  else none

/-- A certificate produced by tryCertify is about exactly the requested law, mass, data. -/
theorem tryCertify_spec (law : ForceExpr) (mass : Scalar) (data : RegressionData)
    (c : CertifiedLaw) (h : tryCertify law mass data = some c) :
    c.law = law ∧ c.mass = mass ∧ c.data = data := by
  unfold tryCertify at h
  split at h
  · cases h
    exact ⟨rfl, rfl, rfl⟩
  · cases h

/-- Occam's razor: smallest expression; ties keep the earlier candidate. -/
def pickBest : List CertifiedLaw → Option CertifiedLaw
  | [] => none
  | c :: cs =>
    some (cs.foldl (fun acc x => if x.law.size < acc.law.size then x else acc) c)

/-! ============================================================
    7. APEX UNIFIED WORLD MODEL
    ============================================================ -/

structure ApexUnifiedModel where
  dt : Scalar
  mass : Scalar
  trajectory : Trajectory
  regression : RegressionData
  survivors : List CertifiedLaw
  selected : Option CertifiedLaw
  momentumConsistent : Bool

/-- `filter` is an optional extra pre-filter (e.g. translationFilter); default keeps all. -/
def buildAndDiscover (dt mass : Scalar) (traj : Trajectory) (candidates : List ForceExpr)
    (filter : ForceExpr → Bool := fun _ => true) : ApexUnifiedModel :=
  let regData := makeRegressionData dt traj
  let survivors := (candidates.filter filter).filterMap (fun law => tryCertify law mass regData)
  { dt := dt,
    mass := mass,
    trajectory := traj,
    regression := regData,
    survivors := survivors,
    selected := pickBest survivors,
    momentumConsistent := isMomentumConsistent mass regData }

/-- Whatever law is selected, it fits every regression point exactly. -/
theorem selected_exactFit (M : ApexUnifiedModel) (c : CertifiedLaw)
    (_ : M.selected = some c) : exactLaw c.law c.data c.mass :=
  c.exactFit

theorem selected_not_falsified (M : ApexUnifiedModel) (c : CertifiedLaw)
    (_ : M.selected = some c) : ¬ falsified c.law c.data c.mass :=
  c.antiFalsification

/-! ============================================================
    8. EXAMPLE: data generated by the SAME discrete scheme (Störmer–Verlet)
    ============================================================ -/

/-- q_{n+1} = 2 q_n - q_{n-1} - dt² (k/m) q_n ; returns n+2 positions. -/
def verlet (dt m k : Scalar) : Nat → Scalar → Scalar → List Scalar
  | 0, q0, q1 => [q0, q1]
  | n + 1, q0, q1 => q0 :: verlet dt m k n q1 (2 * q1 - q0 - dt * dt * k * q1 / m)

/-- Build samples with centered momentum p = m (c - a) / (2 dt) at each interior point. -/
def samplesOf (dt m : Scalar) (t : Nat) : List Scalar → Trajectory
  | a :: b :: c :: rest =>
      ⟨t, ⟨b, m * ((c - a) / (2 * dt))⟩⟩ :: samplesOf dt m (t + 1) (b :: c :: rest)
  | _ => []

namespace Example

def springLaw (k : Scalar) : ForceExpr :=
  .neg (.cast (by decide) (.mul (.const ⟨1, 0, -2⟩ k) .q))

def dampLaw (c : Scalar) : ForceExpr :=
  .neg (.cast (by decide) (.mul (.const ⟨1, 0, -1⟩ c) .v))

def zeroLaw : ForceExpr := .const Dim.force 0

def demoTraj : Trajectory := samplesOf (1 / 10) 1 0 (verlet (1 / 10) 1 1 10 1 1)

def demoModel : ApexUnifiedModel :=
  buildAndDiscover (1 / 10) 1 demoTraj [zeroLaw, dampLaw 1, springLaw 2, springLaw 1]

-- expected: survivors = 1 (spring k = 1), selected size = 4, momentum consistent = true
#eval demoModel.survivors.length
#eval demoModel.selected.map (fun c => c.law.size)
#eval demoModel.momentumConsistent

end Example

end Unified
end UHA
