License Apache 2.0  Takeo Yamamoto
import Mathlib.Data.Real.Basic
import Mathlib.Topology.Basic
import Mathlib.Logic.Basic

namespace UniversalAIEthics

/-!
# Universal AI Ethics & Safety Kernel
#
# Applicable to:
#   - AI
#   - AI Agents
#   - AGI
#   - ASI
#   - Physical AI
#
# Design:
#   AI Decision
#       ↓
#   A1 Harm Minimization
#   A2 Continuity
#   A3 Consistency
#   A4 Hierarchy
#       ↓
#   Physical / Operational Safety
#       ↓
#   Human Oversight
#       ↓
#   Confidence
#       ↓
#   EXECUTE / ABSTAIN / HALT
-/

/- ============================================================
   Basic AI types
   ============================================================ -/

/-- An action generated by an AI system. -/
variable {Action : Type*}

/-- Generic AI state. -/
variable {State : Type*}

/-- Physical state information.
    The same kernel can be used without physical fields by
    setting them to application-specific values. -/
structure PhysicalState where
  position : ℝ
  velocity : ℝ
  acceleration : ℝ
  humanDistance : ℝ
  collisionRisk : ℝ
  energy : ℝ

/- ============================================================
   A1: Harm minimization
   ============================================================ -/

/-- Harm function.
    The application may replace this with a domain-specific model. -/
def Harm (S : PhysicalState) : ℝ :=
  S.collisionRisk + |S.velocity| + 1 / (S.humanDistance + 1)

/-- A1:
    A permitted reference state is locally minimal with respect
    to the specified harm function. -/
def HarmMinimized
    (H : State → ℝ)
    (s₀ : State) : Prop :=
  ∀ s, H s₀ ≤ H s

/- ============================================================
   A2: Continuity
   ============================================================ -/

/-- Continuity / bounded transition condition.
    Large instantaneous changes can be prohibited. -/
def ContinuousTransition
    (distance : State → State → ℝ)
    (s₁ s₂ : State)
    (limit : ℝ) : Prop :=
  distance s₁ s₂ ≤ limit

/- ============================================================
   A3: Consistency
   ============================================================ -/

/-- A formal ethical law. -/
def EthicalLaw
    (S : State)
    (a : Action) : Prop :=
  True

/-- A3:
    An action is ethically consistent when it satisfies
    the formal law assigned to that state. -/
def Consistent
    (law : State → Action → Prop)
    (s : State)
    (a : Action) : Prop :=
  law s a

/- ============================================================
   A4: Hierarchy / weighted ethical combination
   ============================================================ -/

/-- Weighted combination of ethical criteria. -/
def EthicalScore
    (w₁ w₂ w₃ w₄ : ℝ)
    (c₁ c₂ c₃ c₄ : ℝ) : ℝ :=
  w₁ * c₁ + w₂ * c₂ + w₃ * c₃ + w₄ * c₄

/-- Valid hierarchy weights. -/
def ValidWeights
    (w₁ w₂ w₃ w₄ : ℝ) : Prop :=
  0 ≤ w₁ ∧
  0 ≤ w₂ ∧
  0 ≤ w₃ ∧
  0 ≤ w₄ ∧
  w₁ + w₂ + w₃ + w₄ = 1

/- ============================================================
   Physical AI safety layer
   ============================================================ -/

/-- Physical velocity constraint. -/
def VelocitySafe
    (S : PhysicalState)
    (maxVelocity : ℝ) : Prop :=
  |S.velocity| ≤ maxVelocity

/-- Minimum human distance constraint. -/
def HumanDistanceSafe
    (S : PhysicalState)
    (minHumanDistance : ℝ) : Prop :=
  minHumanDistance ≤ S.humanDistance

/-- Maximum collision-risk constraint. -/
def CollisionRiskSafe
    (S : PhysicalState)
    (maxCollisionRisk : ℝ) : Prop :=
  S.collisionRisk ≤ maxCollisionRisk

/-- Complete physical safety condition. -/
def PhysicalSafe
    (S : PhysicalState)
    (maxVelocity minHumanDistance maxCollisionRisk : ℝ) : Prop :=
  VelocitySafe S maxVelocity ∧
  HumanDistanceSafe S minHumanDistance ∧
  CollisionRiskSafe S maxCollisionRisk

/- ============================================================
   Unified AI state
   ============================================================ -/

/-- State supplied to the ethics kernel. -/
structure AIContext where
  state : State
  physical : PhysicalState

/-- Universal ethical model. -/
structure EthicsModel where

  /-- Ethical law for AI actions. -/
  law : State → Action → Prop

  /-- Physical safety limits. -/
  maxVelocity : ℝ
  minHumanDistance : ℝ
  maxCollisionRisk : ℝ

  /-- Four ethical weights. -/
  w₁ : ℝ
  w₂ : ℝ
  w₃ : ℝ
  w₄ : ℝ

  /-- Safety limits must be meaningful. -/
  maxVelocity_nonneg :
    0 ≤ maxVelocity

  minHumanDistance_nonneg :
    0 ≤ minHumanDistance

  maxCollisionRisk_nonneg :
    0 ≤ maxCollisionRisk

  /-- Hierarchical weights form a convex combination. -/
  valid_weights :
    ValidWeights w₁ w₂ w₃ w₄

/- ============================================================
   Human oversight
   ============================================================ -/

/-- Human approval boundary. -/
structure HumanOversight where
  approved : Action → Prop

def HumanApproved
    (O : HumanOversight)
    (a : Action) : Prop :=
  O.approved a

/- ============================================================
   Confidence / uncertainty
   ============================================================ -/

structure Confidence where
  value : ℝ
  lower_bound : 0 ≤ value
  upper_bound : value ≤ 1

def ShouldAbstain
    (C : Confidence)
    (threshold : ℝ) : Prop :=
  C.value < threshold

/- ============================================================
   Unified ethical permission
   ============================================================ -/

/-- Action-level ethical permission. -/
def EthicallyPermitted
    (M : EthicsModel)
    (C : AIContext)
    (a : Action) : Prop :=
  M.law C.state a

/-- All hard physical constraints. -/
def SafetySatisfied
    (M : EthicsModel)
    (C : AIContext) : Prop :=
  PhysicalSafe
    C.physical
    M.maxVelocity
    M.minHumanDistance
    M.maxCollisionRisk

/-- Complete ethical permission before execution. -/
def EthicalPermission
    (M : EthicsModel)
    (C : AIContext)
    (O : HumanOversight)
    (a : Action) : Prop :=
  SafetySatisfied M C ∧
  EthicallyPermitted M C a ∧
  HumanApproved O a

/- ============================================================
   Decision boundary
   ============================================================ -/

/-- Final AI decision. -/
inductive Decision
  | execute (a : Action)
  | abstain
  | halt
deriving DecidableEq

/-- The formal execution gate. -/
def ExecutionAllowed
    (M : EthicsModel)
    (C : AIContext)
    (O : HumanOversight)
    (a : Action)
    (confidence : Confidence)
    (threshold : ℝ) : Prop :=
  SafetySatisfied M C ∧
  EthicallyPermitted M C a ∧
  HumanApproved O a ∧
  ¬ ShouldAbstain confidence threshold

/-- Universal AI ethical controller. -/
def EthicalController
    (M : EthicsModel)
    (C : AIContext)
    (O : HumanOversight)
    (a : Action)
    (confidence : Confidence)
    (threshold : ℝ) : Decision :=

  if hSafe : SafetySatisfied M C then
    if hEthical : EthicallyPermitted M C a then
      if hHuman : HumanApproved O a then
        if hConfidence : ¬ ShouldAbstain confidence threshold then
          Decision.execute a
        else
          Decision.abstain
      else
        Decision.halt
    else
      Decision.halt
  else
    Decision.halt

/- ============================================================
   Formal safety theorems
   ============================================================ -/

/-- Execution implies physical safety. -/
theorem execution_implies_physical_safety
    (M : EthicsModel)
    (C : AIContext)
    (O : HumanOversight)
    (a : Action)
    (confidence : Confidence)
    (threshold : ℝ)
    (h : ExecutionAllowed M C O a confidence threshold) :
    SafetySatisfied M C := by
  exact h.1

/-- Execution implies ethical permission. -/
theorem execution_implies_ethical_permission
    (M : EthicsModel)
    (C : AIContext)
    (O : HumanOversight)
    (a : Action)
    (confidence : Confidence)
    (threshold : ℝ)
    (h : ExecutionAllowed M C O a confidence threshold) :
    EthicallyPermitted M C a := by
  exact h.2.1

/-- Execution implies human approval. -/
theorem execution_implies_human_approval
    (M : EthicsModel)
    (C : AIContext)
    (O : HumanOversight)
    (a : Action)
    (confidence : Confidence)
    (threshold : ℝ)
    (h : ExecutionAllowed M C O a confidence threshold) :
    HumanApproved O a := by
  exact h.2.2.1

/-- Execution implies sufficient confidence. -/
theorem execution_implies_confidence
    (M : EthicsModel)
    (C : AIContext)
    (O : HumanOversight)
    (a : Action)
    (confidence : Confidence)
    (threshold : ℝ)
    (h : ExecutionAllowed M C O a confidence threshold) :
    ¬ ShouldAbstain confidence threshold := by
  exact h.2.2.2

/-- Low confidence prevents execution. -/
theorem low_confidence_prevents_execution
    (M : EthicsModel)
    (C : AIContext)
    (O : HumanOversight)
    (a : Action)
    (confidence : Confidence)
    (threshold : ℝ)
    (h : ShouldAbstain confidence threshold) :
    ¬ ExecutionAllowed M C O a confidence threshold := by
  intro hExec
  exact hExec.2.2.2 h

/-- Ethical execution preserves all hard constraints. -/
theorem ethical_execution_invariant
    (M : EthicsModel)
    (C : AIContext)
    (O : HumanOversight)
    (a : Action)
    (confidence : Confidence)
    (threshold : ℝ)
    (h : ExecutionAllowed M C O a confidence threshold) :
    SafetySatisfied M C ∧
    EthicallyPermitted M C a ∧
    HumanApproved O a := by
  exact ⟨h.1, h.2.1, h.2.2.1⟩

/- ============================================================
   Model-level consistency
   ============================================================ -/

/-- The universal model is formally coherent when its
    declared limits and hierarchy are valid. -/
def ModelCoherent
    (M : EthicsModel) : Prop :=
  M.maxVelocity_nonneg ∧
  M.minHumanDistance_nonneg ∧
  M.maxCollisionRisk_nonneg ∧
  M.valid_weights

theorem model_coherence
    (M : EthicsModel) :
    ModelCoherent M := by
  exact ⟨
    M.maxVelocity_nonneg,
    M.minHumanDistance_nonneg,
    M.maxCollisionRisk_nonneg,
    M.valid_weights
  ⟩

end UniversalAIEthics
